//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;
import java.sql.*;

public class Forget_Password extends JPanel {
    private JButton jcomp1;
    private JButton jcomp2;
    private JLabel jcomp3;
    private JLabel jcomp4;
    private JLabel jcomp5;
    private JTextField jcomp6;
    private JTextField jcomp7;
    private JTextField jcomp8;

    public Forget_Password() {
        //construct components
        jcomp1 = new JButton ("OK");
		jcomp1.addActionListener( new jcomp1() );
        jcomp2 = new JButton ("Cancel");
		jcomp2.addActionListener( new jcomp2() );
        jcomp3 = new JLabel ("Question :");
        jcomp4 = new JLabel ("Answer :");
        jcomp5 = new JLabel ("User Name / ID :");
        jcomp6 = new JTextField (5);
        jcomp7 = new JTextField (5);
        jcomp8 = new JTextField (5);

        //adjust size and set layout
        setPreferredSize (new Dimension (308, 176));
        setLayout (null);

        //add components
        add (jcomp1);
        add (jcomp2);
        add (jcomp3);
        add (jcomp4);
        add (jcomp5);
        add (jcomp6);
        add (jcomp7);
        add (jcomp8);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds (125, 125, 80, 25);
        jcomp2.setBounds (210, 125, 80, 25);
        jcomp3.setBounds (25, 55, 100, 25);
        jcomp4.setBounds (25, 85, 100, 25);
        jcomp5.setBounds (25, 25, 100, 25);
        jcomp6.setBounds (125, 25, 165, 25);
        jcomp7.setBounds (125, 55, 165, 25);
        jcomp8.setBounds (125, 85, 165, 25);
    }
	class jcomp1 implements ActionListener
	{
		public void actionPerformed( ActionEvent e )
		{
		try
			{
			String unm="";
			Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
			Connection con= DriverManager.getConnection("jdbc:odbc:data");
			Statement stm= con.createStatement();
			ResultSet rset = stm.executeQuery("select UID,Question,Answer,Password from Light");
			String data="";
			while(rset.next())
			{
				data += rset.getString(1)+" "+rset.getString(5)+" "+rset.getString(6)+" "+rset.getString(2)+"\n";
				if(rset.getString(1)==jcomp6.getText() && rset.getString(5)==jcomp7.getText() && rset.getString(6)==jcomp6.getText())
				{
					JOptionPane.showMessageDialog(null,"\nUser ID : "+jcomp5.getText()+".\n Password : " + rset.getString(2),
					"Your Account Information :", JOptionPane.INFORMATION_MESSAGE );
				}
			}
			}
		catch(Exception e1)
			{
			}	
			

		}
	}
	class jcomp2 implements ActionListener
	{
		public void actionPerformed( ActionEvent e )
		{
			
		}
	}
}
