//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class login extends JPanel {
    private JLabel jcomp1;
    private JLabel jcomp2;
    private JPasswordField jcomp3;
    private JTextField jcomp4;
    private JButton jcomp5;
    private JMenuBar log_mnu;

    public login() {
        //construct preComponents
        JMenu userMenu = new JMenu ("User");
        JMenuItem registrationItem = new JMenuItem ("Registration");
		registrationItem.addActionListener( new registrationItem() );
        userMenu.add (registrationItem);
        JMenuItem forgot_passwordItem = new JMenuItem ("Forgot Password");
        forgot_passwordItem.addActionListener( new forgot_passwordItem() );
        userMenu.add (forgot_passwordItem);
        JMenuItem exitItem = new JMenuItem ("Exit");
        exitItem.addActionListener( new exitItem() );
        userMenu.add (exitItem);
        JMenu helpMenu = new JMenu ("Help");
        JMenuItem contentsItem = new JMenuItem ("Contents");
        helpMenu.add (contentsItem);
        JMenuItem aboutItem = new JMenuItem ("About");
        helpMenu.add (aboutItem);

        //construct components
        jcomp1 = new JLabel ("User Name / ID");
        jcomp2 = new JLabel ("Password");
        jcomp3 = new JPasswordField (5);
        jcomp4 = new JTextField (5);
        jcomp5 = new JButton ("Login");
        jcomp5.addActionListener( new jcomp5() );
        log_mnu = new JMenuBar();
        log_mnu.add (userMenu);
        log_mnu.add (helpMenu);

        //adjust size and set layout
        setPreferredSize (new Dimension (298, 146));
        setLayout (null);

        //add components
        add (jcomp1);
        add (jcomp2);
        add (jcomp3);
        add (jcomp4);
        add (jcomp5);
        add (log_mnu);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds (20, 40, 100, 25);
        jcomp2.setBounds (20, 70, 100, 25);
        jcomp3.setBounds (115, 70, 165, 25);
        jcomp4.setBounds (115, 40, 165, 25);
        jcomp5.setBounds (210, 100, 70, 25);
        log_mnu.setBounds (0, 0, 300, 25);
    }
	class jcomp5 implements ActionListener
	{
		public void actionPerformed( ActionEvent e )
		{
			
		}
	}
	class registrationItem implements ActionListener
	{
		public void actionPerformed( ActionEvent e )
		{
        JFrame frame = new JFrame ("Register");
        frame.setDefaultCloseOperation (JFrame.HIDE_ON_CLOSE);
        frame.getContentPane().add (new Register());
        frame.pack();
        frame.setVisible (true);
		}
	}
	class forgot_passwordItem implements ActionListener
	{
		public void actionPerformed( ActionEvent e )
		{
        JFrame frame = new JFrame ("Forget_Password");
        frame.setDefaultCloseOperation (JFrame.HIDE_ON_CLOSE);
        frame.getContentPane().add (new Forget_Password());
        frame.pack();
        frame.setVisible (true);
		}
	}
	class exitItem implements ActionListener
	{
		public void actionPerformed( ActionEvent e )
		{
        JFrame frame = new JFrame ("login");
        frame.setDefaultCloseOperation (JFrame.HIDE_ON_CLOSE);
        frame.getContentPane().add (new login());
        frame.pack();
        frame.setVisible (false);
		}
	}

    public static void main (String[] args) {
        JFrame frame = new JFrame ("login");
        frame.setDefaultCloseOperation (JFrame.HIDE_ON_CLOSE);
        frame.getContentPane().add (new login());
        frame.pack();
        frame.setVisible (true);
    }
}
