//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;
import java.sql.*;

public class Register extends JPanel implements ItemListener
	 {
    private JButton jcomp1;
    private JButton jcomp2;
    private JLabel jcomp3;
    private JLabel jcomp4;
    private JLabel jcomp5;
    private JLabel jcomp6;
    private JLabel jcomp7;
    private JLabel jcomp8;
    private JLabel jcomp9;
    private JLabel jcomp10;
    private JLabel jcomp11;
    private JLabel jcomp12;
    private JLabel jcomp13;
    private JLabel jcomp14;
    private JTextField jcomp15;
    private JPasswordField jcomp16;
    private JPasswordField jcomp17;
    private JTextField jcomp18;
    private JTextField jcomp19;
    private JComboBox jcomp20;
    private JTextField jcomp21;
    private JComboBox jcomp22;
    private JComboBox jcomp23;
    private JComboBox jcomp24;
    private JTextField jcomp25;
    private JTextArea jcomp26;
    public static String que="",country="",age="",sex="";
	
	public Register()
 	{
		
        //construct preComponents
        String[] jcomp20Items = {"What is your pet name ?", "Which color do you like ?", "Where you want go for honimoon ?", "What is your nick name ?", "What is your lover name ?"};
        String[] jcomp22Items = {"Africa", "Astrelia", "Bangladesh", "Brazil", "Chaina", "India", "Irak", "Iran", "Kubed", "Nepal", "Pakistan", "Srilanka", "Tibat", "UK", "US"};
        String[] jcomp23Items = {"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100"};
        String[] jcomp24Items = {"Male", "Female"};

        //construct components
        jcomp1 = new JButton ("Register");
		jcomp1.addActionListener( new jcomp1() );
        jcomp2 = new JButton ("Cancel");
		jcomp2.addActionListener( new jcomp2() );
        jcomp3 = new JLabel ("User ID :");
        jcomp4 = new JLabel ("Password :");
        jcomp5 = new JLabel ("Confirm :");
        jcomp6 = new JLabel ("First Name :");
        jcomp7 = new JLabel ("Last Name :");
        jcomp8 = new JLabel ("Question :");
        jcomp9 = new JLabel ("Answer :");
        jcomp10 = new JLabel ("Country :");
        jcomp11 = new JLabel ("Age :");
        jcomp12 = new JLabel ("Sex :");
        jcomp13 = new JLabel ("E-mail :");
        jcomp14 = new JLabel ("Discription :");
        jcomp15 = new JTextField (5);
        jcomp16 = new JPasswordField (5);
        jcomp17 = new JPasswordField (5);
        jcomp18 = new JTextField (5);
        jcomp19 = new JTextField (5);
        jcomp20 = new JComboBox (jcomp20Items);
	jcomp20.addItemListener(this);
        jcomp21 = new JTextField (5);
        jcomp22 = new JComboBox (jcomp22Items);
	jcomp22.addItemListener(this);	
        jcomp23 = new JComboBox (jcomp23Items);
	jcomp23.addItemListener(this);
        jcomp24 = new JComboBox (jcomp24Items);
	jcomp24.addItemListener(this);
        jcomp25 = new JTextField (5);
        jcomp26 = new JTextArea (5, 5);

        //adjust size and set layout
        setPreferredSize (new Dimension (425, 491));
        setLayout (null);

        //add components
        add (jcomp1);
        add (jcomp2);
        add (jcomp3);
        add (jcomp4);
        add (jcomp5);
        add (jcomp6);
        add (jcomp7);
        add (jcomp8);
        add (jcomp9);
        add (jcomp10);
        add (jcomp11);
        add (jcomp12);
        add (jcomp13);
        add (jcomp14);
        add (jcomp15);
        add (jcomp16);
        add (jcomp17);
        add (jcomp18);
        add (jcomp19);
        add (jcomp20);
        add (jcomp21);
        add (jcomp22);
        add (jcomp23);
        add (jcomp24);
        add (jcomp25);
        add (jcomp26);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds (195, 445, 100, 25);
        jcomp2.setBounds (300, 445, 100, 25);
        jcomp3.setBounds (30, 25, 100, 25);
        jcomp4.setBounds (30, 55, 100, 25);
        jcomp5.setBounds (30, 85, 85, 25);
        jcomp6.setBounds (30, 115, 85, 25);
        jcomp7.setBounds (30, 145, 100, 25);
        jcomp8.setBounds (30, 175, 100, 25);
        jcomp9.setBounds (30, 205, 100, 25);
        jcomp10.setBounds (30, 235, 100, 25);
        jcomp11.setBounds (30, 265, 100, 25);
        jcomp12.setBounds (30, 295, 100, 25);
        jcomp13.setBounds (30, 325, 100, 25);
        jcomp14.setBounds (30, 355, 100, 25);
        jcomp15.setBounds (115, 25, 200, 25);
        jcomp16.setBounds (115, 55, 180, 25);
        jcomp17.setBounds (115, 85, 180, 25);
        jcomp18.setBounds (115, 115, 180, 25);
        jcomp19.setBounds (115, 145, 180, 25);
        jcomp20.setBounds (115, 175, 200, 25);
        jcomp21.setBounds (115, 205, 200, 25);
        jcomp22.setBounds (115, 235, 100, 25);
        jcomp23.setBounds (115, 265, 100, 25);
        jcomp24.setBounds (115, 295, 100, 25);
        jcomp25.setBounds (115, 325, 290, 25);
        jcomp26.setBounds (115, 355, 290, 80);
    }
	
	public void itemStateChanged(ItemEvent ie)
		{
		if(ie.getSource()==jcomp20)
			{
			if(ie.getStateChange()==ItemEvent.SELECTED)
				{
				que=(String)ie.getItem();
				}
			}
		if(ie.getSource()==jcomp22)
			{
			if(ie.getStateChange()==ItemEvent.SELECTED)
				{
				country=(String)ie.getItem();
				}
			}
		if(ie.getSource()==jcomp23)
			{
			if(ie.getStateChange()==ItemEvent.SELECTED)
				{
				age=(String)ie.getItem();
				}
			}
		if(ie.getSource()==jcomp24)
			{
			if(ie.getStateChange()==ItemEvent.SELECTED)
				{
				sex=(String)ie.getItem();
				}
			}
		
		
		}
	class jcomp1 implements ActionListener
	{
	

		public void actionPerformed( ActionEvent e )
		{
		String uname=jcomp15.getText();
		String pass=jcomp16.getText();
		String fname=jcomp18.getText();
		String lname=jcomp19.getText();
		String ans=jcomp21.getText();
		String email=jcomp25.getText();
		String desc=jcomp26.getText();
		
			try
			{
				Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
				Connection con= DriverManager.getConnection("jdbc:odbc:data");
				Statement stm= con.createStatement();
				
				String sql="insert into user values('"+uname+"','"+pass+"','"+fname+"','"+lname+"','"+que+"','"+ans+"','"+country+"','"+age+"','"+sex+"','"+email+"','"+desc+"')";

				stm.executeUpdate(sql);
				JOptionPane.showMessageDialog(null,"Registered ","Registered Successfully", JOptionPane.ERROR_MESSAGE );
				//this.setVisible(false);		
				//rset.next();
				//rset.close();
				stm.close();
				con.close();
			}
			catch(ClassNotFoundException e1)
			{
			}
			catch(SQLException se)
			{
					JOptionPane.showMessageDialog(null,"Error : " + se.getMessage(),
					"Error Message :", JOptionPane.ERROR_MESSAGE );
			}
			
		}
	}
	class jcomp2 implements ActionListener
	{
		public void actionPerformed( ActionEvent e )
		{
			
		}
	}
}
