/*
JavaScript Image Slider Platinum 2.0
(C)1999-2008 Usingit.com, All rights reserved!
http://www.usingit.com/products/webtoolkit
http://www.usingit.com/support
*/
CISlider1(['slider0.jpg','','_self','This script was generated by JavaScript Image Slider Platinum from usingit.com!',408,608]);
CISlider1(['slider1.jpg','','_self','This script was generated by JavaScript Image Slider Platinum from usingit.com!',404,608]);
CISlider1(['slider2.jpg','','_self','This script was generated by JavaScript Image Slider Platinum from usingit.com!',426,608]);
CISlider1(['slider3.jpg','','_self','This script was generated by JavaScript Image Slider Platinum from usingit.com!',404,608]);
CISlider1(['slider4.jpg','','_self','This script was generated by JavaScript Image Slider Platinum from usingit.com!',404,608]);
CISlider1(['slider5.jpg','','_self','This script was generated by JavaScript Image Slider Platinum from usingit.com!',456,608]);
CISlider1(['slider6.jpg','','_self','This script was generated by JavaScript Image Slider Platinum from usingit.com!',427,608]);
function CISlider1(ipa){
if(!(window.Slider1cfg)){eval('window.Slider1cfg=new Array();');};
Slider1cfg[Slider1cfg.length]=ipa;};
function InitSlider1(){
if (!window.bWax){setTimeout('InitSlider1()',350);return;};
new Bcax('Slider1_div',600,616,1,15,0,0,'FFFFFF',Slider1cfg,4,0,0,'loading_w.gif','Slider1_Loading',0);};
InitSlider1();
