<%@ Page Language="C#" MasterPageFile="~/LoginMaster.master" AutoEventWireup="true" CodeFile="CreateUser.aspx.cs" Inherits="CreateUser" Title="BDC Converter - Create User" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="cc1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <asp:UpdatePanel ID="UpdatePanel1" runat="server">
        <contenttemplate>
<TABLE style="BORDER-RIGHT: dodgerblue 1px solid; BORDER-TOP: dodgerblue 1px solid; FONT-SIZE: 10pt; BORDER-LEFT: dodgerblue 1px solid; WIDTH: 400px; BORDER-BOTTOM: dodgerblue 1px solid; FONT-FAMILY: Verdana; HEIGHT: 200px; BACKGROUND-COLOR: #cddefc"><TBODY><TR><TD style="HEIGHT: 20px; BACKGROUND-COLOR: #1c84c5; TEXT-ALIGN: center" colSpan=3><STRONG><SPAN style="COLOR: white">Create New User</SPAN></STRONG></TD></TR><TR><TD style="HEIGHT: 20px; TEXT-ALIGN: right" colSpan=3></TD></TR><TR><TD style="TEXT-ALIGN: right"><asp:Label id="lblUserName" runat="server" Text="User Name:"></asp:Label></TD><TD style="WIDTH: 5%; TEXT-ALIGN: left"></TD><TD style="TEXT-ALIGN: left"><asp:TextBox id="txtUserName" tabIndex=10 runat="server" BorderWidth="1px" BorderStyle="Solid" BorderColor="#1C84C5" BackColor="White" Width="150px" MaxLength="30" ValidationGroup="valid1"></asp:TextBox><asp:RequiredFieldValidator id="RequiredFieldValidator1" runat="server" ControlToValidate="txtUserName" Display="None" ErrorMessage="<b>Required field missing</b></br>User Name should not be blank." ValidationGroup="valid1"></asp:RequiredFieldValidator></TD></TR><TR><TD style="TEXT-ALIGN: right"><asp:Label id="lblGroup" runat="server" Text="Group:"></asp:Label></TD><TD style="TEXT-ALIGN: left"></TD><TD style="TEXT-ALIGN: left"><asp:DropDownList id="drdnGroup" tabIndex=11 runat="server" Width="153px" AutoPostBack="True" OnSelectedIndexChanged="drdnGroup_SelectedIndexChanged"></asp:DropDownList></TD></TR><TR><TD style="TEXT-ALIGN: right"><asp:Label id="lblPassword" runat="server" Text="Password:"></asp:Label></TD><TD></TD><TD style="TEXT-ALIGN: left"><asp:TextBox id="txtPassword" tabIndex=12 runat="server" BorderWidth="1px" BorderStyle="Solid" BorderColor="#1C84C5" BackColor="White" Width="150px" TextMode="Password" ValidationGroup="valid1"></asp:TextBox><cc1:PasswordStrength id="PasswordStrength1" runat="server" BarBorderCssClass="BarBorder_TextBox2" MinimumNumericCharacters="1" MinimumSymbolCharacters="1" PreferredPasswordLength="15" RequiresUpperAndLowerCaseCharacters="True" StrengthIndicatorType="BarIndicator" StrengthStyles="BarIndicator_TextBox2_weak;BarIndicator_TextBox2_average;BarIndicator_TextBox2_good" TargetControlID="txtPassword" TextStrengthDescriptions="Very Poor;Weak;Average;Strong;Excellent">
                    </cc1:PasswordStrength> <asp:RequiredFieldValidator id="RequiredFieldValidator2" runat="server" ControlToValidate="txtPassword" Display="None" ErrorMessage="<b>Required field missing</b></br>Password should not be blank." ValidationGroup="valid1"></asp:RequiredFieldValidator></TD></TR><TR><TD style="TEXT-ALIGN: right"><asp:Label id="lblConfirmPass" runat="server" Text="Confirm Password:"></asp:Label></TD><TD></TD><TD style="TEXT-ALIGN: left"><asp:TextBox id="txtConfirmPass" tabIndex=13 runat="server" BorderWidth="1px" BorderStyle="Solid" BorderColor="#1C84C5" BackColor="White" Width="150px" TextMode="Password" ValidationGroup="valid1"></asp:TextBox><asp:RequiredFieldValidator id="RequiredFieldValidator3" runat="server" ControlToValidate="txtConfirmPass" Display="None" ErrorMessage="<b>Required field missing</b></br>Confirm Password should not be blank." ValidationGroup="valid1"></asp:RequiredFieldValidator></TD></TR><TR><TD style="WIDTH: 100px; TEXT-ALIGN: right"></TD><TD></TD><TD style="WIDTH: 150px; TEXT-ALIGN: right"></TD></TR><TR><TD style="TEXT-ALIGN: center" colSpan=3><cc1:ValidatorCalloutExtender id="ValidatorCalloutExtender1" runat="server" TargetControlID="RequiredFieldValidator1">
                </cc1:ValidatorCalloutExtender> <cc1:ValidatorCalloutExtender id="ValidatorCalloutExtender2" runat="server" TargetControlID="RequiredFieldValidator2">
                </cc1:ValidatorCalloutExtender> <cc1:ValidatorCalloutExtender id="ValidatorCalloutExtender3" runat="server" TargetControlID="RequiredFieldValidator3">
                </cc1:ValidatorCalloutExtender> <asp:Label id="lblMsg" runat="server" Font-Size="8pt" ForeColor="Green"></asp:Label> <asp:Label id="lblError" runat="server" Font-Size="8pt" ForeColor="Red"></asp:Label></TD></TR><TR><TD style="TEXT-ALIGN: right"></TD><TD></TD><TD style="TEXT-ALIGN: left"><asp:Button id="btnCreateUser" tabIndex=14 onclick="btnCreateUser_Click" runat="server" Text="Create User" BorderWidth="1px" BorderStyle="Solid" BorderColor="#1C84C5" BackColor="White" ValidationGroup="valid1"></asp:Button></TD></TR><TR><TD style="TEXT-ALIGN: right"></TD><TD></TD><TD style="HEIGHT: 5px; TEXT-ALIGN: right"></TD></TR></TBODY></TABLE>
</contenttemplate>
    </asp:UpdatePanel>
</asp:Content>

