<%@ Page Language="C#" MasterPageFile="~/LoginMaster.master" AutoEventWireup="true" CodeFile="UserGroup.aspx.cs" Inherits="UserGroup" Title="User Group" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <asp:UpdatePanel id="UpdatePanel1" runat="server">
        <contenttemplate>
<TABLE style="BORDER-RIGHT: dodgerblue 1px solid; BORDER-TOP: dodgerblue 1px solid; FONT-SIZE: 10pt; BORDER-LEFT: dodgerblue 1px solid; WIDTH: 400px; BORDER-BOTTOM: dodgerblue 1px solid; FONT-FAMILY: Verdana; HEIGHT: 200px; BACKGROUND-COLOR: #cddefc"><TBODY><TR><TD style="HEIGHT: 20px; BACKGROUND-COLOR: #1c84c5; TEXT-ALIGN: center" colSpan=3><STRONG><SPAN style="COLOR: #ffffff">User Group</SPAN></STRONG></TD></TR><TR><TD style="HEIGHT: 20px; TEXT-ALIGN: right" colSpan=3></TD></TR><TR><TD style="TEXT-ALIGN: right"><asp:Label id="lblUserName" runat="server" Text="User Name:"></asp:Label></TD><TD style="WIDTH: 5%; TEXT-ALIGN: left"></TD><TD style="TEXT-ALIGN: left"><asp:DropDownList id="drdnUserName" tabIndex=1 runat="server" Width="150px" AutoPostBack="True" OnSelectedIndexChanged="drdnGroupName_SelectedIndexChanged" BackColor="White"></asp:DropDownList></TD></TR><TR><TD style="VERTICAL-ALIGN: middle; TEXT-ALIGN: right"><asp:Label id="lblGroup" runat="server" Text="Group:"></asp:Label></TD><TD style="TEXT-ALIGN: left"></TD><TD style="TEXT-ALIGN: left"><asp:DropDownList id="drdnGroup" runat="server" Width="150px" AutoPostBack="True" OnSelectedIndexChanged="drdnGroup_SelectedIndexChanged"></asp:DropDownList></TD></TR><TR><TD style="WIDTH: 100px; TEXT-ALIGN: right"></TD><TD></TD><TD style="WIDTH: 150px; TEXT-ALIGN: right"></TD></TR><TR><TD style="TEXT-ALIGN: center" colSpan=3><asp:Label id="lblError" runat="server" ForeColor="Red" Font-Size="8pt"></asp:Label> <asp:Label id="lblMsg" runat="server" ForeColor="Green" Font-Size="8pt"></asp:Label></TD></TR><TR><TD style="TEXT-ALIGN: right"></TD><TD></TD><TD style="TEXT-ALIGN: left"><asp:Button id="btnAssGroup" tabIndex=3 onclick="btnAssPermission_Click" runat="server" Width="108px" Text="Assign Group" BackColor="White" BorderColor="#1C84C5" BorderStyle="Solid" BorderWidth="1px"></asp:Button></TD></TR><TR><TD style="TEXT-ALIGN: right"></TD><TD></TD><TD style="HEIGHT: 5px; TEXT-ALIGN: right"></TD></TR></TBODY></TABLE>
</contenttemplate>
    </asp:UpdatePanel>
</asp:Content>

