/*
JavaScript FadeIn SlideShow 1.0
(C)1999-2006 Usingit.com, All rights reserved!
http://www.usingit.com/products/webtoolkit
http://www.usingit.com/support
*/
CIFadeInSlideShow1(['gallary/slider0.jpg','','_self','This script was generated by JavaScript FadeIn SlideShow from usingit.com',736,125]);
CIFadeInSlideShow1(['gallary/slider1.jpg','','_self','This script was generated by JavaScript FadeIn SlideShow from usingit.com',500,125]);
CIFadeInSlideShow1(['gallary/slider2.jpg','','_self','This script was generated by JavaScript FadeIn SlideShow from usingit.com',667,125]);
CIFadeInSlideShow1(['gallary/slider3.jpg','','_self','This script was generated by JavaScript FadeIn SlideShow from usingit.com',515,125]);
CIFadeInSlideShow1(['gallary/slider4.jpg','','_self','This script was generated by JavaScript FadeIn SlideShow from usingit.com',649,125]);
CIFadeInSlideShow1(['gallary/slider5.jpg','','_self','This script was generated by JavaScript FadeIn SlideShow from usingit.com',649,125]);
function CIFadeInSlideShow1(ipa){
if(!(window.FadeInSlideShow1cfg)){eval('window.FadeInSlideShow1cfg=new Array();');};
FadeInSlideShow1cfg[FadeInSlideShow1cfg.length]=ipa;};
function InitFadeInSlideShow1(){
if (!window.bkag){setTimeout('InitFadeInSlideShow1()',350);return;};
new bPaf('FadeInSlideShow1','FadeInSlideShow1_div',650,125,'FFFFFF',1000,30,FadeInSlideShow1cfg,0);};
InitFadeInSlideShow1();
