<?php
// This script and data application were generated by PHPMagic 3.1 on 9/20/2008 at 8:22:12 PM
// Download PHPMagic for free from http://www.websitedatabases.com/


error_reporting(E_ALL ^ E_NOTICE);
if(is_array($_POST)){
	$HTTP_POST_VARS=$_POST;
}
if(is_array($_GET)){
	$HTTP_GET_VARS=$_GET;
}
if(is_array($_FILES)){
	$HTTP_POST_FILES=$_FILES;
}
include(dirname(__FILE__)."/datalist.php");

if(!@is_file(dirname(__FILE__)."/config.php")){
	echo StyleSheet() . "\n\n<div class=Error>";
	echo $Translation["error:"].' ';
	echo $Translation["if you haven't set up"];
	echo "</div>";
	exit;
}

include(dirname(__FILE__)."/config.php");
function sql($statment,$assoc=1)
{
	
	global $Translation;
	global $dbServer, $dbUsername, $dbPassword, $dbDatabase;
	
		$dbhost = "localhost";
		$dbuser = "";
		$dbpass = "";
		$dbname = "new_db";
		
		/****** Connect to MySQL ******/
		if(!mysql_connect($dbServer, $dbUsername, $dbPassword)){
			echo StyleSheet() . "\n\n<div class=Error>";
			echo $Translation["error:"] . mysql_error();
			echo "</div>";
			exit;
		}
		/****** Select DB ********/
		if(!mysql_select_db($dbDatabase)){
			echo StyleSheet() . "\n\n<div class=Error>";
			echo $Translation["error:"] . mysql_error();
			echo $Translation["if you haven't set up"];
			echo "</div>";
			exit;
		}
	
	if(!$result = mysql_query($statment))
	{
			echo StyleSheet() . "\n\n<div class=Error>";
		echo "<br><b>" . $Translation["sql error:"] . "</b><br><br>
		     <strong>" . $Translation["query:"] . "</strong><br> $statment<br><br>
		     " . mysql_error();
			if(stristr($statment, "select ")) echo ".<br>" . $Translation["if you haven't set up"];
			echo "</div>";
			echo "<a href=\"javascript:history.go(-1);\">" . $Translation["< back"] . "</a>";
		exit;
	}
	return $result;
}

function NavMenus()
{
	global $Translation;

	$t = time();
	$menu  = "<select name=nav_menu onChange='window.location=document.myform.nav_menu.options[document.myform.nav_menu.selectedIndex].value;'>";
	$menu .= "<option value='#' class=SelectedOption style='color:black;'>" . $Translation["select a table"] . "</option>";
	$menu .= "<option value='index.html' class=SelectedOption style='color:black;'>" . $Translation["homepage"] . "</option>";
	$menu .= "<option value='table1_view.php?t=$t' class=SelectedOption>form</option>";
	$menu .= "</select>";
	return $menu;
}

function StyleSheet()
{
	return "<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">";
}
function PrepareUploadedFile($FieldName, $MaxSize, $FileTypes='jpg|jpeg|gif|png', $NoRename=false){
	global $HTTP_POST_FILES, $Translation;
	$f = $HTTP_POST_FILES[$FieldName];

	if($f['error'] != 4 && $f['name']!=''){
		if($f['size']>$MaxSize || $f['error']){
			echo StyleSheet()."<div class=Error>Error: The file you uploaded exceeds the maximum allowed size of " . intval($MaxSize/1024) . " KB. <a href=".$_SERVER['HTTP_REFERER'].">Back to table</a>.</div>";
			exit;
		}
		if(!eregi('\.('.$FileTypes.')$', $f['name'], $ft)){
			echo StyleSheet()."<div class=Error>Error: This file type is not allowed. Only ".str_replace('|', ', ', $FileTypes)." files can be uploaded. <a href=".$_SERVER['HTTP_REFERER'].">Back to table</a>.</div>";
			exit;
		}

		if($NoRename){
			$n  = str_replace(' ', '_', $f['name']);
		}else{
			$n  = microtime();
			$n  = str_replace(' ', '_', $n);
			$n  = str_replace('0.', '', $n);
			$n .= $ft[0];
		}

		if(!file_exists($Translation['ImageFolder'])){
			@mkdir($Translation['ImageFolder'], 0777);
		}

		if(!@move_uploaded_file($f['tmp_name'], $Translation['ImageFolder'] . $n)){
			echo StyleSheet()."<div class=Error>Error: Couldn't save the uploaded file. Try chmoding the upload folder '".$Translation['ImageFolder']."' to 777. <a href=".$_SERVER['HTTP_REFERER'].">Back to table</a>.</div>";
			exit;
		}else{
			@chmod($Translation['ImageFolder'].$n, 0666);
			return $n;
		}
	}
	return "";
}
?>