<?php

// Data functions for table table1

// This script and data application were generated by PHPMagic 3.1 on 9/20/2008 at 8:22:12 PM
// Download PHPMagic for free from http://www.websitedatabases.com/

function insert()
{
	global $HTTP_SERVER_VARS, $HTTP_GET_VARS, $HTTP_POST_VARS, $HTTP_POST_FILES, $Translation;
	
	if(get_magic_quotes_gpc())
	{
		$field2 = $HTTP_POST_VARS["field2"];
	}
	else
	{
		$field2 = addslashes($HTTP_POST_VARS["field2"]);
	}
	$field1 = PrepareUploadedFile('field1', 20480,'', true);
	if($field2 == "") {echo StyleSheet() . "\n\n<div class=Error>" . $Translation["error:"] . " 'rno': " . $Translation['pkfield empty'] . "</div>"; exit;}

	
	sql("insert into table1 (field1, field2) values (" . (($field1 != "") ? "'$field1'" : "NULL") . ", " . (($field2 != "") ? "'$field2'" : "NULL") . ")");
	return $field2;
}

function delete($selected_id)
{
	// insure referential integrity ...
	global $Translation;


	// delete file stored in the 'field1' field
	$res = sql("select field1 from table1 where field2='$selected_id'");
	if($row=@mysql_fetch_row($res)){
		if($row[0]!=''){
			@unlink($Translation['ImageFolder'].$row[0]);
		}
	}

	sql("delete from table1 where field2='$selected_id'");
}

function update($selected_id)
{
	global $HTTP_SERVER_VARS, $HTTP_GET_VARS, $HTTP_POST_VARS, $Translation;
	
	if(get_magic_quotes_gpc())
	{
		$field2 = $HTTP_POST_VARS["field2"];
	}
	else
	{
		$field2 = addslashes($HTTP_POST_VARS["field2"]);
	}

	if($HTTP_POST_VARS['field1_remove'] == 1){
		$field1 = '';
		// delete file from server
		$res = sql("select field1 from table1 where field2='$selected_id'");
		if($row=@mysql_fetch_row($res)){
			if($row[0]!=''){
				@unlink($Translation['ImageFolder'].$row[0]);
			}
		}
	}else{
		$field1 = PrepareUploadedFile('field1', 20480, '', true);
		// delete file from server
		if($field1 != ''){
			$res = sql("select field1 from table1 where field2='$selected_id'");
			if($row=@mysql_fetch_row($res)){
				if($row[0]!=''){
					@unlink($Translation['ImageFolder'].$row[0]);
				}
			}
		}
	}
	sql("update table1 set " . ($field1!="" ? "field1='$field1'" : ($HTTP_POST_VARS['field1_remove'] != 1 ? "field1=field1" : "field1=NULL")) . ", " . "field2=" . (($field2 != "") ? "'$field2'" : "NULL") . " where field2='$selected_id'");
}

function form($selected_id = "", $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1)
{
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.
	
	global $Translation;
	
	if(!$AllowInsert && $selected_id==""){  return ""; }
	
	

	if($selected_id)
	{
		$res = sql("select * from table1 where field2='$selected_id'");
		$row = mysql_fetch_array($res);
	}
	
	// code for template based detail view forms
	
	// open the detail view template
	$templateCode=@implode('', @file('./table1_templateDV.html'));
	
	// process form title
	$templateCode=str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detail View', $templateCode);
	// process buttons
	if($AllowInsert){
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', "<input type=image src=insert.gif name=insert alt='" . $Translation['add new record'] . "'>", $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}
	if($selected_id){
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', "<input type=image src=update.gif vspace=1 name=update alt='" . $Translation["update record"] . "'>", $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if($AllowDelete){
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', "<input type=image src=delete.gif vspace=1 name=delete alt='" . $Translation['delete record'] . "' onClick=\"return confirm('" . $Translation['are you sure?'] . "');\">", $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', "<input type=image src=deselect.gif vspace=1 name=deselect alt='" . $Translation['deselect record'] . "'>", $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}
	
	// process combos
	
	// process images
	$templateCode=str_replace('<%%UPLOADFILE(field1)%%>', '<input type=hidden name=MAX_FILE_SIZE value=0>'.$Translation['upload image'].' <input type=file name="field1" class=TextBox>', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(field2)%%>', '', $templateCode);
	
	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(field1)%%>', htmlspecialchars($row['field1'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(field2)%%>', htmlspecialchars($row['field2'], ENT_QUOTES), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(field1)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(field2)%%>', '', $templateCode);
	}
	
	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}
	
	// finally, clear scrap
	$templateCode=str_replace('<%%', '<!--', $templateCode);
	$templateCode=str_replace('%%>', '-->', $templateCode);

	return $templateCode;
}
?>